### PR TITLE
feat(blockquotes): add blockquotes plugin

### PR DESCRIPTION
**Pull request by brendancarney**

### CODE REVIEW

**Comment by slig** [comment]
Hi everyone! First of all, thanks for your time publishing this work here on GH.

I'd love to use this plugin and if there's anything that is blocking it from being published, maybe I can help with it. Thanks!

**Comment by brendancarney** [comment]
Hey @slig, I haven't had time to iron out the bugs here yet, but I'm happy to merge this and release as an alpha version if you want to play around with it. Just a warning that it's probably not quite production ready, and we're not using it in production yet.

**Comment by slig** [comment]
Thank you very much!

**Comment by brendancarney** [comment]
Published as `@convertkit/slate-blockquotes@0.0.3`. 

Feel free to file issues as you run into them. Thanks for checking it out!

**Pull request merged**
